# Generated by Django 5.0 on 2024-06-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
