# Generated by Django 5.0 on 2024-02-03 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATTRIBUTES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name_plural': 'ATTRIBUTES',
            },
        ),
        migrations.CreateModel(
            name='BRAND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'BRANDS',
            },
        ),
        migrations.CreateModel(
            name='ATTRIBUTEVALUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(blank=True, max_length=50, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.attributes')),
            ],
            options={
                'verbose_name_plural': 'ATTRIBUTEVALUE',
            },
        ),
        migrations.CreateModel(
            name='PRODUCTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('in_stocks', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('attributevalue', models.ManyToManyField(to='Inventory.attributevalue')),
                ('brandname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
            ],
            options={
                'verbose_name_plural': 'PRODUCTS',
            },
        ),
        migrations.CreateModel(
            name='PRICE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleprice', models.DecimalField(decimal_places=2, default=False, max_digits=4)),
                ('storeprice', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('text', models.TextField(max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.products')),
            ],
            options={
                'verbose_name_plural': 'PRICES',
            },
        ),
        migrations.CreateModel(
            name='IMAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='products')),
                ('text', models.TextField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.products')),
            ],
            options={
                'verbose_name_plural': 'IMAGES',
            },
        ),
        migrations.CreateModel(
            name='STOCKS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quntity', models.PositiveIntegerField(default=0)),
                ('last_checked', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventory.products')),
            ],
            options={
                'verbose_name_plural': 'STOCKS',
            },
        ),
    ]
