# Generated by Django 5.0 on 2024-04-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_alter_products_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributevalue',
            old_name='valueName',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='attributevalue',
            old_name='values',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='Chest',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='Length',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='sleve',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
