# Generated by Django 5.0 on 2024-05-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_rename_valuename_attributevalue_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
