# Generated by Django 5.0 on 2024-02-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_price_discount_alter_price_saleprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='quntity',
        ),
        migrations.AddField(
            model_name='stocks',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
