# Generated by Django 5.0 on 2024-02-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_remove_stocks_quntity_stocks_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='discount',
            new_name='discount_percentage',
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brandImage'),
        ),
        migrations.AddField(
            model_name='brand',
            name='maid_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
