# Generated by Django 5.0 on 2024-02-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_price_tag_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
