# Generated by Django 5.0 on 2024-02-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_alter_price_discount_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='tag_price',
            new_name='mrp',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='valueName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='imgLink',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
