# Generated by Django 5.0 on 2024-02-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_subcategory_is_active_subcategory_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'SUBCATEGORYS'},
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='Subcategory'),
        ),
    ]
