# Generated by Django 5.0 on 2024-02-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_alter_subcategory_options_alter_subcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imgLink',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
