# Generated by Django 5.0 on 2024-02-20 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_brand_company_stocks_stocks_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('gm', 'gm'), ('litre', 'ltr'), ('pcs', 'pcs'), ('each', 'each'), ('pkg', 'pkg')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.attributes'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='valueName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
