# Generated by Django 5.0 on 2024-02-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0014_stocks_unit_alter_attributevalue_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='barcode',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
