# Generated by Django 5.0 on 2024-02-26 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0016_alter_image_imglink_alter_image_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.products'),
        ),
    ]
