# Generated by Django 5.0 on 2024-03-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0017_alter_stocks_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='stocks_qty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
