# Generated by Django 5.0 on 2024-03-10 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0018_alter_stocks_quantity_alter_stocks_stocks_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='stock_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.stocks'),
        ),
    ]
