# Generated by Django 5.0 on 2024-03-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0019_price_stock_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='stock_price',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
    ]
