# Generated by Django 5.0 on 2024-03-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0020_rename_stock_price_price_stock_remove_price_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='total_store_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
