# Generated by Django 5.0 on 2024-03-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0021_price_total_store_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='price',
            name='total_store_price',
        ),
        migrations.AlterField(
            model_name='stocks',
            name='stocks_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
