# Generated by Django 5.0 on 2024-03-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0022_remove_price_mrp_remove_price_total_store_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='storeprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='stocks_qty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
