# Generated by Django 5.0 on 2024-03-16 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0023_alter_price_storeprice_alter_stocks_stocks_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='company',
            new_name='name',
        ),
    ]
