# Generated by Django 5.0 on 2024-03-30 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='Reviews')),
                ('noOfReview', models.PositiveIntegerField()),
                ('commentDate', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.products')),
            ],
            options={
                'verbose_name_plural': 'REVIEWS',
            },
        ),
    ]
