# Generated by Django 5.0 on 2024-02-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Reviews'),
        ),
    ]
