# Generated by Django 5.0 on 2024-03-20 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0025_price_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CART',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.image')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.products')),
                ('qty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.stocks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CARTS',
            },
        ),
    ]
