# Generated by Django 5.0 on 2024-03-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='imgage',
            new_name='image',
        ),
    ]
