# Generated by Django 5.0 on 2024-03-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_rename_imgage_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
    ]
