# Generated by Django 5.0 on 2024-05-10 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cart_qnty_price'),
        ('Inventory', '0003_rename_valuename_attributevalue_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='qnty_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.price'),
        ),
    ]
